#VARIABLES LAS CUALES FACILITAN CAMBIAR CIERTOS VALORES, TAMAÑO, VELOCIDAD, COLOR, ETC

#!tamano(px), ancho - alto
#! VENTANA
ANCHO_VENTANA = 1020
ALTO_VENTANA = 780

#! PERSONAJE
ANCHO_PJ = 20
ALTO_PJ = 40
COLOR_PJ = (0,0,255)

#! VELOCIDAD
VELOCIDAD = 10   # pixeles/s

#! FONDO
COLOR_BG = (0,0,25)

#! FPS
FPS = 90